package br.com.yacamin.rafael.domain.scylla.entity.indicator.i1mn;

import br.com.yacamin.rafael.domain.scylla.entity.indicator.MicrostructureIndicatorEntity;
import lombok.Data;
import org.springframework.data.cassandra.core.cql.Ordering;
import org.springframework.data.cassandra.core.cql.PrimaryKeyType;
import org.springframework.data.cassandra.core.mapping.Column;
import org.springframework.data.cassandra.core.mapping.PrimaryKeyColumn;
import org.springframework.data.cassandra.core.mapping.Table;
import java.time.Instant;

@Data
@Table("microstructure_indicator_1_mn")
public class MicrostructureIndicator1MnEntity implements MicrostructureIndicatorEntity {
    @PrimaryKeyColumn(name = "symbol", type = PrimaryKeyType.PARTITIONED)
    private String symbol;
    @PrimaryKeyColumn(name = "open_time", type = PrimaryKeyType.CLUSTERED, ordering = Ordering.ASCENDING)
    @Column("open_time")
    private Instant openTime;
    @Column("mic_amihud_acc_w10") private double mic_amihud_acc_w10;
    @Column("mic_amihud_acc_w16") private double mic_amihud_acc_w16;
    @Column("mic_amihud_acc_w4") private double mic_amihud_acc_w4;
    @Column("mic_amihud_acc_w5") private double mic_amihud_acc_w5;
    @Column("mic_amihud_slp_w20") private double mic_amihud_slp_w20;
    @Column("mic_amihud_slp_w4") private double mic_amihud_slp_w4;
    @Column("mic_body_atr_ratio") private double mic_body_atr_ratio;
    @Column("mic_body_perc") private double mic_body_perc;
    @Column("mic_body_ratio") private double mic_body_ratio;
    @Column("mic_body_ratio_slp_w10") private double mic_body_ratio_slp_w10;
    @Column("mic_body_return") private double mic_body_return;
    @Column("mic_body_run_len") private double mic_body_run_len;
    @Column("mic_body_shock_atrn") private double mic_body_shock_atrn;
    @Column("mic_body_sign_prst_w20") private double mic_body_sign_prst_w20;
    @Column("mic_candle_balance_score") private double mic_candle_balance_score;
    @Column("mic_candle_body_center_position") private double mic_candle_body_center_position;
    @Column("mic_candle_body_pct") private double mic_candle_body_pct;
    @Column("mic_candle_body_ratio") private double mic_candle_body_ratio;
    @Column("mic_candle_body_slp_w10") private double mic_candle_body_slp_w10;
    @Column("mic_candle_body_slp_w20") private double mic_candle_body_slp_w20;
    @Column("mic_candle_body_strength_score") private double mic_candle_body_strength_score;
    @Column("mic_candle_brr") private double mic_candle_brr;
    @Column("mic_candle_close_pos_norm") private double mic_candle_close_pos_norm;
    @Column("mic_candle_energy_atrn") private double mic_candle_energy_atrn;
    @Column("mic_candle_energy_raw") private double mic_candle_energy_raw;
    @Column("mic_candle_lmr") private double mic_candle_lmr;
    @Column("mic_candle_lower_wick_pct") private double mic_candle_lower_wick_pct;
    @Column("mic_candle_pressure_raw") private double mic_candle_pressure_raw;
    @Column("mic_candle_range") private double mic_candle_range;
    @Column("mic_candle_shadow_ratio") private double mic_candle_shadow_ratio;
    @Column("mic_candle_spread_ratio") private double mic_candle_spread_ratio;
    @Column("mic_candle_strength") private double mic_candle_strength;
    @Column("mic_candle_total_wick_atrn") private double mic_candle_total_wick_atrn;
    @Column("mic_candle_total_wick_pct") private double mic_candle_total_wick_pct;
    @Column("mic_candle_upper_wick_pct") private double mic_candle_upper_wick_pct;
    @Column("mic_candle_volatility_inside") private double mic_candle_volatility_inside;
    @Column("mic_candle_wick_body_alignment") private double mic_candle_wick_body_alignment;
    @Column("mic_candle_wick_dominance") private double mic_candle_wick_dominance;
    @Column("mic_candle_wick_exhaustion") private double mic_candle_wick_exhaustion;
    @Column("mic_candle_wick_imbalance") private double mic_candle_wick_imbalance;
    @Column("mic_candle_wick_imbalance_norm") private double mic_candle_wick_imbalance_norm;
    @Column("mic_candle_wick_imbalance_slp_w10") private double mic_candle_wick_imbalance_slp_w10;
    @Column("mic_candle_wick_pressure_score") private double mic_candle_wick_pressure_score;
    @Column("mic_close_hlc3_atrn") private double mic_close_hlc3_atrn;
    @Column("mic_close_open_norm") private double mic_close_open_norm;
    @Column("mic_close_open_ratio") private double mic_close_open_ratio;
    @Column("mic_close_pos_norm") private double mic_close_pos_norm;
    @Column("mic_close_pos_slp_w20") private double mic_close_pos_slp_w20;
    @Column("mic_close_to_high_norm") private double mic_close_to_high_norm;
    @Column("mic_close_to_low_norm") private double mic_close_to_low_norm;
    @Column("mic_close_triangle_score_atrn") private double mic_close_triangle_score_atrn;
    @Column("mic_close_vwap_atrn") private double mic_close_vwap_atrn;
    @Column("mic_extreme_range_return") private double mic_extreme_range_return;
    @Column("mic_gap_ratio") private double mic_gap_ratio;
    @Column("mic_hasb_lambda_w16_slp_w20") private double mic_hasb_lambda_w16_slp_w20;
    @Column("mic_hasb_lambda_w48_slp_w20") private double mic_hasb_lambda_w48_slp_w20;
    @Column("mic_high_return") private double mic_high_return;
    @Column("mic_kyle_lambda_w16_acc_w10") private double mic_kyle_lambda_w16_acc_w10;
    @Column("mic_kyle_lambda_w16_acc_w16") private double mic_kyle_lambda_w16_acc_w16;
    @Column("mic_kyle_lambda_w16_acc_w4") private double mic_kyle_lambda_w16_acc_w4;
    @Column("mic_kyle_lambda_w16_acc_w5") private double mic_kyle_lambda_w16_acc_w5;
    @Column("mic_kyle_lambda_w16_slp_w20") private double mic_kyle_lambda_w16_slp_w20;
    @Column("mic_kyle_lambda_w16_slp_w4") private double mic_kyle_lambda_w16_slp_w4;
    @Column("mic_kyle_lambda_w4_acc_w10") private double mic_kyle_lambda_w4_acc_w10;
    @Column("mic_kyle_lambda_w4_acc_w16") private double mic_kyle_lambda_w4_acc_w16;
    @Column("mic_kyle_lambda_w4_acc_w4") private double mic_kyle_lambda_w4_acc_w4;
    @Column("mic_kyle_lambda_w4_acc_w5") private double mic_kyle_lambda_w4_acc_w5;
    @Column("mic_kyle_lambda_w4_slp_w20") private double mic_kyle_lambda_w4_slp_w20;
    @Column("mic_kyle_lambda_w4_slp_w4") private double mic_kyle_lambda_w4_slp_w4;
    @Column("mic_log_range_slp_w20") private double mic_log_range_slp_w20;
    @Column("mic_low_return") private double mic_low_return;
    @Column("mic_lower_wick_return") private double mic_lower_wick_return;
    @Column("mic_range_acc_w10") private double mic_range_acc_w10;
    @Column("mic_range_acc_w5") private double mic_range_acc_w5;
    @Column("mic_range_asymmetry") private double mic_range_asymmetry;
    @Column("mic_range_atr_ratio") private double mic_range_atr_ratio;
    @Column("mic_range_atrn") private double mic_range_atrn;
    @Column("mic_range_compression_w20") private double mic_range_compression_w20;
    @Column("mic_range_headroom_atr") private double mic_range_headroom_atr;
    @Column("mic_range_return") private double mic_range_return;
    @Column("mic_range_slp_w10") private double mic_range_slp_w10;
    @Column("mic_range_slp_w20") private double mic_range_slp_w20;
    @Column("mic_range_squeeze_w20") private double mic_range_squeeze_w20;
    @Column("mic_range_stdn") private double mic_range_stdn;
    @Column("mic_roll_spread_acc_w16") private double mic_roll_spread_acc_w16;
    @Column("mic_roll_spread_acc_w32") private double mic_roll_spread_acc_w32;
    @Column("mic_roll_spread_acc_w48") private double mic_roll_spread_acc_w48;
    @Column("mic_roll_spread_slp_w16") private double mic_roll_spread_slp_w16;
    @Column("mic_roll_spread_slp_w32") private double mic_roll_spread_slp_w32;
    @Column("mic_roll_spread_slp_w48") private double mic_roll_spread_slp_w48;
    @Column("mic_shadow_imbalance_score") private double mic_shadow_imbalance_score;
    @Column("mic_tr_atrn") private double mic_tr_atrn;
    @Column("mic_tr_range_ratio") private double mic_tr_range_ratio;
    @Column("mic_true_range") private double mic_true_range;
    @Column("mic_upper_wick_return") private double mic_upper_wick_return;
    @Column("mic_wick_imbalance") private double mic_wick_imbalance;
    @Column("mic_wick_perc_down") private double mic_wick_perc_down;
    @Column("mic_wick_perc_up") private double mic_wick_perc_up;
}
