package br.com.yacamin.rafael.application.service.model;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.*;
import java.util.stream.IntStream;

@Slf4j
@Service
public class HeadHunterFeaturesMap {

    @FunctionalInterface
    public interface FloatExtractor<T> {
        float get(T t);
    }

    public record FeatureDef(String key, FloatExtractor<AssemblerDto> fn) {}

    private static final List<FeatureDef> REGISTRY = List.of(
            new FeatureDef("mic_roll_spread_acc_w16", d -> (float) d.getMic().getMic_roll_spread_acc_w16()),
            new FeatureDef("mic_roll_spread_acc_w32", d -> (float) d.getMic().getMic_roll_spread_acc_w32()),
            new FeatureDef("mic_roll_spread_acc_w48", d -> (float) d.getMic().getMic_roll_spread_acc_w48()),
            new FeatureDef("mic_roll_spread_slp_w16", d -> (float) d.getMic().getMic_roll_spread_slp_w16()),
            new FeatureDef("mic_roll_spread_slp_w32", d -> (float) d.getMic().getMic_roll_spread_slp_w32()),
            new FeatureDef("mic_roll_spread_slp_w48", d -> (float) d.getMic().getMic_roll_spread_slp_w48()),
            new FeatureDef("mic_amihud_slp_w4", d -> (float) d.getMic().getMic_amihud_slp_w4()),
            new FeatureDef("mic_amihud_slp_w20", d -> (float) d.getMic().getMic_amihud_slp_w20()),
            new FeatureDef("mic_amihud_acc_w4", d -> (float) d.getMic().getMic_amihud_acc_w4()),
            new FeatureDef("mic_amihud_acc_w5", d -> (float) d.getMic().getMic_amihud_acc_w5()),
            new FeatureDef("mic_amihud_acc_w10", d -> (float) d.getMic().getMic_amihud_acc_w10()),
            new FeatureDef("mic_amihud_acc_w16", d -> (float) d.getMic().getMic_amihud_acc_w16()),
            new FeatureDef("mic_kyle_lambda_w4_slp_w4", d -> (float) d.getMic().getMic_kyle_lambda_w4_slp_w4()),
            new FeatureDef("mic_kyle_lambda_w4_slp_w20", d -> (float) d.getMic().getMic_kyle_lambda_w4_slp_w20()),
            new FeatureDef("mic_kyle_lambda_w16_slp_w4", d -> (float) d.getMic().getMic_kyle_lambda_w16_slp_w4()),
            new FeatureDef("mic_kyle_lambda_w16_slp_w20", d -> (float) d.getMic().getMic_kyle_lambda_w16_slp_w20()),
            new FeatureDef("mic_kyle_lambda_w4_acc_w4", d -> (float) d.getMic().getMic_kyle_lambda_w4_acc_w4()),
            new FeatureDef("mic_kyle_lambda_w4_acc_w5", d -> (float) d.getMic().getMic_kyle_lambda_w4_acc_w5()),
            new FeatureDef("mic_kyle_lambda_w4_acc_w10", d -> (float) d.getMic().getMic_kyle_lambda_w4_acc_w10()),
            new FeatureDef("mic_kyle_lambda_w4_acc_w16", d -> (float) d.getMic().getMic_kyle_lambda_w4_acc_w16()),
            new FeatureDef("mic_kyle_lambda_w16_acc_w4", d -> (float) d.getMic().getMic_kyle_lambda_w16_acc_w4()),
            new FeatureDef("mic_kyle_lambda_w16_acc_w5", d -> (float) d.getMic().getMic_kyle_lambda_w16_acc_w5()),
            new FeatureDef("mic_kyle_lambda_w16_acc_w10", d -> (float) d.getMic().getMic_kyle_lambda_w16_acc_w10()),
            new FeatureDef("mic_kyle_lambda_w16_acc_w16", d -> (float) d.getMic().getMic_kyle_lambda_w16_acc_w16()),
            new FeatureDef("mic_hasb_lambda_w16_slp_w20", d -> (float) d.getMic().getMic_hasb_lambda_w16_slp_w20()),
            new FeatureDef("mic_hasb_lambda_w48_slp_w20", d -> (float) d.getMic().getMic_hasb_lambda_w48_slp_w20()),
            new FeatureDef("mic_range_atrn", d -> (float) d.getMic().getMic_range_atrn()),
            new FeatureDef("mic_range_stdn", d -> (float) d.getMic().getMic_range_stdn()),
            new FeatureDef("mic_range_atr_ratio", d -> (float) d.getMic().getMic_range_atr_ratio()),
            new FeatureDef("mic_range_slp_w10", d -> (float) d.getMic().getMic_range_slp_w10()),
            new FeatureDef("mic_range_slp_w20", d -> (float) d.getMic().getMic_range_slp_w20()),
            new FeatureDef("mic_range_acc_w5", d -> (float) d.getMic().getMic_range_acc_w5()),
            new FeatureDef("mic_range_acc_w10", d -> (float) d.getMic().getMic_range_acc_w10()),
            new FeatureDef("mic_range_compression_w20", d -> (float) d.getMic().getMic_range_compression_w20()),
            new FeatureDef("mic_log_range_slp_w20", d -> (float) d.getMic().getMic_log_range_slp_w20()),
            new FeatureDef("mic_range_return", d -> (float) d.getMic().getMic_range_return()),
            new FeatureDef("mic_high_return", d -> (float) d.getMic().getMic_high_return()),
            new FeatureDef("mic_low_return", d -> (float) d.getMic().getMic_low_return()),
            new FeatureDef("mic_extreme_range_return", d -> (float) d.getMic().getMic_extreme_range_return()),
            new FeatureDef("mic_candle_range", d -> (float) d.getMic().getMic_candle_range()),
            new FeatureDef("mic_candle_volatility_inside", d -> (float) d.getMic().getMic_candle_volatility_inside()),
            new FeatureDef("mic_candle_spread_ratio", d -> (float) d.getMic().getMic_candle_spread_ratio()),
            new FeatureDef("mic_candle_brr", d -> (float) d.getMic().getMic_candle_brr()),
            new FeatureDef("mic_candle_lmr", d -> (float) d.getMic().getMic_candle_lmr()),
            new FeatureDef("mic_true_range", d -> (float) d.getMic().getMic_true_range()),
            new FeatureDef("mic_tr_atrn", d -> (float) d.getMic().getMic_tr_atrn()),
            new FeatureDef("mic_tr_range_ratio", d -> (float) d.getMic().getMic_tr_range_ratio()),
            new FeatureDef("mic_range_squeeze_w20", d -> (float) d.getMic().getMic_range_squeeze_w20()),
            new FeatureDef("mic_range_asymmetry", d -> (float) d.getMic().getMic_range_asymmetry()),
            new FeatureDef("mic_range_headroom_atr", d -> (float) d.getMic().getMic_range_headroom_atr()),
            new FeatureDef("mic_gap_ratio", d -> (float) d.getMic().getMic_gap_ratio()),
            new FeatureDef("mic_candle_body_pct", d -> (float) d.getMic().getMic_candle_body_pct()),
            new FeatureDef("mic_body_perc", d -> (float) d.getMic().getMic_body_perc()),
            new FeatureDef("mic_body_ratio", d -> (float) d.getMic().getMic_body_ratio()),
            new FeatureDef("mic_body_atr_ratio", d -> (float) d.getMic().getMic_body_atr_ratio()),
            new FeatureDef("mic_candle_body_ratio", d -> (float) d.getMic().getMic_candle_body_ratio()),
            new FeatureDef("mic_candle_body_center_position", d -> (float) d.getMic().getMic_candle_body_center_position()),
            new FeatureDef("mic_candle_pressure_raw", d -> (float) d.getMic().getMic_candle_pressure_raw()),
            new FeatureDef("mic_candle_strength", d -> (float) d.getMic().getMic_candle_strength()),
            new FeatureDef("mic_candle_body_strength_score", d -> (float) d.getMic().getMic_candle_body_strength_score()),
            new FeatureDef("mic_candle_energy_atrn", d -> (float) d.getMic().getMic_candle_energy_atrn()),
            new FeatureDef("mic_body_ratio_slp_w10", d -> (float) d.getMic().getMic_body_ratio_slp_w10()),
            new FeatureDef("mic_candle_body_slp_w10", d -> (float) d.getMic().getMic_candle_body_slp_w10()),
            new FeatureDef("mic_candle_body_slp_w20", d -> (float) d.getMic().getMic_candle_body_slp_w20()),
            new FeatureDef("mic_body_return", d -> (float) d.getMic().getMic_body_return()),
            new FeatureDef("mic_body_shock_atrn", d -> (float) d.getMic().getMic_body_shock_atrn()),
            new FeatureDef("mic_body_sign_prst_w20", d -> (float) d.getMic().getMic_body_sign_prst_w20()),
            new FeatureDef("mic_body_run_len", d -> (float) d.getMic().getMic_body_run_len()),
            new FeatureDef("mic_candle_upper_wick_pct", d -> (float) d.getMic().getMic_candle_upper_wick_pct()),
            new FeatureDef("mic_candle_lower_wick_pct", d -> (float) d.getMic().getMic_candle_lower_wick_pct()),
            new FeatureDef("mic_wick_perc_up", d -> (float) d.getMic().getMic_wick_perc_up()),
            new FeatureDef("mic_wick_perc_down", d -> (float) d.getMic().getMic_wick_perc_down()),
            new FeatureDef("mic_candle_total_wick_pct", d -> (float) d.getMic().getMic_candle_total_wick_pct()),
            new FeatureDef("mic_candle_total_wick_atrn", d -> (float) d.getMic().getMic_candle_total_wick_atrn()),
            new FeatureDef("mic_upper_wick_return", d -> (float) d.getMic().getMic_upper_wick_return()),
            new FeatureDef("mic_lower_wick_return", d -> (float) d.getMic().getMic_lower_wick_return()),
            new FeatureDef("mic_candle_wick_imbalance", d -> (float) d.getMic().getMic_candle_wick_imbalance()),
            new FeatureDef("mic_wick_imbalance", d -> (float) d.getMic().getMic_wick_imbalance()),
            new FeatureDef("mic_candle_wick_imbalance_norm", d -> (float) d.getMic().getMic_candle_wick_imbalance_norm()),
            new FeatureDef("mic_candle_wick_imbalance_slp_w10", d -> (float) d.getMic().getMic_candle_wick_imbalance_slp_w10()),
            new FeatureDef("mic_shadow_imbalance_score", d -> (float) d.getMic().getMic_shadow_imbalance_score()),
            new FeatureDef("mic_candle_wick_pressure_score", d -> (float) d.getMic().getMic_candle_wick_pressure_score()),
            new FeatureDef("mic_candle_shadow_ratio", d -> (float) d.getMic().getMic_candle_shadow_ratio()),
            new FeatureDef("mic_candle_wick_body_alignment", d -> (float) d.getMic().getMic_candle_wick_body_alignment()),
            new FeatureDef("mic_candle_wick_dominance", d -> (float) d.getMic().getMic_candle_wick_dominance()),
            new FeatureDef("mic_candle_wick_exhaustion", d -> (float) d.getMic().getMic_candle_wick_exhaustion()),
            new FeatureDef("mic_close_open_ratio", d -> (float) d.getMic().getMic_close_open_ratio()),
            new FeatureDef("mic_close_open_norm", d -> (float) d.getMic().getMic_close_open_norm()),
            new FeatureDef("mic_close_hlc3_atrn", d -> (float) d.getMic().getMic_close_hlc3_atrn()),
            new FeatureDef("mic_close_vwap_atrn", d -> (float) d.getMic().getMic_close_vwap_atrn()),
            new FeatureDef("mic_close_triangle_score_atrn", d -> (float) d.getMic().getMic_close_triangle_score_atrn()),
            new FeatureDef("mic_candle_balance_score", d -> (float) d.getMic().getMic_candle_balance_score()),
            new FeatureDef("mic_close_pos_slp_w20", d -> (float) d.getMic().getMic_close_pos_slp_w20()),
            new FeatureDef("mic_close_pos_norm", d -> (float) d.getMic().getMic_close_pos_norm()),
            new FeatureDef("mic_candle_close_pos_norm", d -> (float) d.getMic().getMic_candle_close_pos_norm()),
            new FeatureDef("mic_close_to_high_norm", d -> (float) d.getMic().getMic_close_to_high_norm()),
            new FeatureDef("mic_close_to_low_norm", d -> (float) d.getMic().getMic_close_to_low_norm()),
            new FeatureDef("trd_ema_8_slp_atrn", d -> (float) d.getTrd().getTrd_ema_8_slp_atrn()),
            new FeatureDef("trd_ema_20_slp_atrn", d -> (float) d.getTrd().getTrd_ema_20_slp_atrn()),
            new FeatureDef("trd_ema_50_slp_atrn", d -> (float) d.getTrd().getTrd_ema_50_slp_atrn()),
            new FeatureDef("trd_ema_8_slp_acc_atrn", d -> (float) d.getTrd().getTrd_ema_8_slp_acc_atrn()),
            new FeatureDef("trd_ema_20_slp_acc_atrn", d -> (float) d.getTrd().getTrd_ema_20_slp_acc_atrn()),
            new FeatureDef("trd_ema_50_slp_acc_atrn", d -> (float) d.getTrd().getTrd_ema_50_slp_acc_atrn()),
            new FeatureDef("trd_dist_close_ema_8_atrn", d -> (float) d.getTrd().getTrd_dist_close_ema_8_atrn()),
            new FeatureDef("trd_dist_close_ema_20_atrn", d -> (float) d.getTrd().getTrd_dist_close_ema_20_atrn()),
            new FeatureDef("trd_dist_close_ema_50_atrn", d -> (float) d.getTrd().getTrd_dist_close_ema_50_atrn()),
            new FeatureDef("trd_dist_ema_8_20_atrn", d -> (float) d.getTrd().getTrd_dist_ema_8_20_atrn()),
            new FeatureDef("trd_dist_ema_20_50_atrn", d -> (float) d.getTrd().getTrd_dist_ema_20_50_atrn()),
            new FeatureDef("trd_dist_ema_8_50_atrn", d -> (float) d.getTrd().getTrd_dist_ema_8_50_atrn()),
            new FeatureDef("trd_ratio_ema_8_20", d -> (float) d.getTrd().getTrd_ratio_ema_8_20()),
            new FeatureDef("trd_ratio_ema_20_50", d -> (float) d.getTrd().getTrd_ratio_ema_20_50()),
            new FeatureDef("trd_ratio_ema_8_50", d -> (float) d.getTrd().getTrd_ratio_ema_8_50()),
            new FeatureDef("trd_alignment_ema_8_20_50_score", d -> (float) d.getTrd().getTrd_alignment_ema_8_20_50_score()),
            new FeatureDef("trd_alignment_ema_8_20_50_normalized", d -> (float) d.getTrd().getTrd_alignment_ema_8_20_50_normalized()),
            new FeatureDef("trd_aligment_ema_8_20_50_delta", d -> (float) d.getTrd().getTrd_aligment_ema_8_20_50_delta()),
            new FeatureDef("trd_cross_ema_8_20_delta_atrn", d -> (float) d.getTrd().getTrd_cross_ema_8_20_delta_atrn()),
            new FeatureDef("trd_cross_ema_20_50_delta_atrn", d -> (float) d.getTrd().getTrd_cross_ema_20_50_delta_atrn()),
            new FeatureDef("trd_delta_close_ema_8_atrn", d -> (float) d.getTrd().getTrd_delta_close_ema_8_atrn()),
            new FeatureDef("trd_delta_close_ema_20_atrn", d -> (float) d.getTrd().getTrd_delta_close_ema_20_atrn()),
            new FeatureDef("trd_delta_close_ema_50_atrn", d -> (float) d.getTrd().getTrd_delta_close_ema_50_atrn()),
            new FeatureDef("trd_delta_ema_8_20_atrn", d -> (float) d.getTrd().getTrd_delta_ema_8_20_atrn()),
            new FeatureDef("trd_delta_ema_20_50_atrn", d -> (float) d.getTrd().getTrd_delta_ema_20_50_atrn()),
            new FeatureDef("trd_di_diff_14", d -> (float) d.getTrd().getTrd_di_diff_14()),
            new FeatureDef("mom_close_ret_1_atrn", d -> (float) d.getMom().getMom_close_ret_1_atrn()),
            new FeatureDef("mom_close_ret_2_atrn", d -> (float) d.getMom().getMom_close_ret_2_atrn()),
            new FeatureDef("mom_close_ret_3_atrn", d -> (float) d.getMom().getMom_close_ret_3_atrn()),
            new FeatureDef("mom_close_ret_4_atrn", d -> (float) d.getMom().getMom_close_ret_4_atrn()),
            new FeatureDef("mom_close_ret_5_atrn", d -> (float) d.getMom().getMom_close_ret_5_atrn()),
            new FeatureDef("mom_close_ret_6_atrn", d -> (float) d.getMom().getMom_close_ret_6_atrn()),
            new FeatureDef("mom_close_ret_8_atrn", d -> (float) d.getMom().getMom_close_ret_8_atrn()),
            new FeatureDef("mom_close_ret_10_atrn", d -> (float) d.getMom().getMom_close_ret_10_atrn()),
            new FeatureDef("mom_close_ret_12_atrn", d -> (float) d.getMom().getMom_close_ret_12_atrn()),
            new FeatureDef("mom_close_ret_16_atrn", d -> (float) d.getMom().getMom_close_ret_16_atrn()),
            new FeatureDef("mom_burst_10", d -> (float) d.getMom().getMom_burst_10()),
            new FeatureDef("mom_burst_16", d -> (float) d.getMom().getMom_burst_16()),
            new FeatureDef("mom_burst_32", d -> (float) d.getMom().getMom_burst_32()),
            new FeatureDef("mom_cntrate_10", d -> (float) d.getMom().getMom_cntrate_10()),
            new FeatureDef("mom_cntrate_16", d -> (float) d.getMom().getMom_cntrate_16()),
            new FeatureDef("mom_cntrate_32", d -> (float) d.getMom().getMom_cntrate_32()),
            new FeatureDef("mom_decay_10", d -> (float) d.getMom().getMom_decay_10()),
            new FeatureDef("mom_decay_16", d -> (float) d.getMom().getMom_decay_16()),
            new FeatureDef("mom_decay_32", d -> (float) d.getMom().getMom_decay_32()),
            new FeatureDef("mom_impls_10", d -> (float) d.getMom().getMom_impls_10()),
            new FeatureDef("mom_impls_16", d -> (float) d.getMom().getMom_impls_16()),
            new FeatureDef("mom_impls_32", d -> (float) d.getMom().getMom_impls_32()),
            new FeatureDef("mom_chprt_10", d -> (float) d.getMom().getMom_chprt_10()),
            new FeatureDef("mom_chprt_16", d -> (float) d.getMom().getMom_chprt_16()),
            new FeatureDef("mom_chprt_32", d -> (float) d.getMom().getMom_chprt_32()),
            new FeatureDef("mom_rsi_2_dlt", d -> (float) d.getMom().getMom_rsi_2_dlt()),
            new FeatureDef("mom_rsi_3_dlt", d -> (float) d.getMom().getMom_rsi_3_dlt()),
            new FeatureDef("mom_rsi_5_dlt", d -> (float) d.getMom().getMom_rsi_5_dlt()),
            new FeatureDef("mom_rsi_7_dlt", d -> (float) d.getMom().getMom_rsi_7_dlt()),
            new FeatureDef("mom_rsi_14_dlt", d -> (float) d.getMom().getMom_rsi_14_dlt()),
            new FeatureDef("mom_rsi_2_roc", d -> (float) d.getMom().getMom_rsi_2_roc()),
            new FeatureDef("mom_rsi_3_roc", d -> (float) d.getMom().getMom_rsi_3_roc()),
            new FeatureDef("mom_rsi_5_roc", d -> (float) d.getMom().getMom_rsi_5_roc()),
            new FeatureDef("mom_rsi_7_roc", d -> (float) d.getMom().getMom_rsi_7_roc()),
            new FeatureDef("mom_rsi_14_roc", d -> (float) d.getMom().getMom_rsi_14_roc()),
            new FeatureDef("mom_rsi_7_slp", d -> (float) d.getMom().getMom_rsi_7_slp()),
            new FeatureDef("mom_rsi_14_slp", d -> (float) d.getMom().getMom_rsi_14_slp()),
            new FeatureDef("mom_rsi_14_acc", d -> (float) d.getMom().getMom_rsi_14_acc()),
            new FeatureDef("mom_rsi_14_atrn", d -> (float) d.getMom().getMom_rsi_14_atrn()),
            new FeatureDef("mom_rsi_7_dst_mid", d -> (float) d.getMom().getMom_rsi_7_dst_mid()),
            new FeatureDef("mom_rsi_14_dst_mid", d -> (float) d.getMom().getMom_rsi_14_dst_mid()),
            new FeatureDef("mom_rsi_7_tail_up", d -> (float) d.getMom().getMom_rsi_7_tail_up()),
            new FeatureDef("mom_rsi_7_tail_dw", d -> (float) d.getMom().getMom_rsi_7_tail_dw()),
            new FeatureDef("mom_rsi_14_tail_up", d -> (float) d.getMom().getMom_rsi_14_tail_up()),
            new FeatureDef("mom_rsi_14_tail_dw", d -> (float) d.getMom().getMom_rsi_14_tail_dw()),
            new FeatureDef("mom_cmo_14_dlt", d -> (float) d.getMom().getMom_cmo_14_dlt()),
            new FeatureDef("mom_cmo_20_dlt", d -> (float) d.getMom().getMom_cmo_20_dlt()),
            new FeatureDef("mom_cmo_14_dst_mid", d -> (float) d.getMom().getMom_cmo_14_dst_mid()),
            new FeatureDef("mom_cmo_20_dst_mid", d -> (float) d.getMom().getMom_cmo_20_dst_mid()),
            new FeatureDef("mom_wpr_14_dlt", d -> (float) d.getMom().getMom_wpr_14_dlt()),
            new FeatureDef("mom_wpr_28_dlt", d -> (float) d.getMom().getMom_wpr_28_dlt()),
            new FeatureDef("mom_wpr_42_dlt", d -> (float) d.getMom().getMom_wpr_42_dlt()),
            new FeatureDef("mom_wpr_14_dst_mid", d -> (float) d.getMom().getMom_wpr_14_dst_mid()),
            new FeatureDef("mom_wpr_28_dst_mid", d -> (float) d.getMom().getMom_wpr_28_dst_mid()),
            new FeatureDef("mom_wpr_48_dst_mid", d -> (float) d.getMom().getMom_wpr_48_dst_mid()),
            new FeatureDef("mom_stoch_14_k_dlt", d -> (float) d.getMom().getMom_stoch_14_k_dlt()),
            new FeatureDef("mom_stoch_14_d_dlt", d -> (float) d.getMom().getMom_stoch_14_d_dlt()),
            new FeatureDef("mom_stoch_14_spread", d -> (float) d.getMom().getMom_stoch_14_spread()),
            new FeatureDef("mom_stoch_14_k_dst_mid", d -> (float) d.getMom().getMom_stoch_14_k_dst_mid()),
            new FeatureDef("mom_trix_9_dlt", d -> (float) d.getMom().getMom_trix_9_dlt()),
            new FeatureDef("mom_trix_9_hist", d -> (float) d.getMom().getMom_trix_9_hist()),
            new FeatureDef("mom_tsi_25_13_dlt", d -> (float) d.getMom().getMom_tsi_25_13_dlt()),
            new FeatureDef("mom_tsi_25_13_hist", d -> (float) d.getMom().getMom_tsi_25_13_hist()),
            new FeatureDef("mom_tsi_25_13_dst_mid", d -> (float) d.getMom().getMom_tsi_25_13_dst_mid()),
            new FeatureDef("mom_ppo_hist_12_26_9", d -> (float) d.getMom().getMom_ppo_hist_12_26_9()),
            new FeatureDef("mom_ppo_12_26_dlt", d -> (float) d.getMom().getMom_ppo_12_26_dlt()),
            new FeatureDef("mom_ppo_hist_12_26_9_dlt", d -> (float) d.getMom().getMom_ppo_hist_12_26_9_dlt()),
            new FeatureDef("mom_close_3_slp", d -> (float) d.getMom().getMom_close_3_slp()),
            new FeatureDef("mom_close_8_slp", d -> (float) d.getMom().getMom_close_8_slp()),
            new FeatureDef("mom_close_14_slp", d -> (float) d.getMom().getMom_close_14_slp()),
            new FeatureDef("mom_close_3_slp_atrn", d -> (float) d.getMom().getMom_close_3_slp_atrn()),
            new FeatureDef("mom_close_8_slp_atrn", d -> (float) d.getMom().getMom_close_8_slp_atrn()),
            new FeatureDef("mom_close_14_slp_atrn", d -> (float) d.getMom().getMom_close_14_slp_atrn()),
            new FeatureDef("mom_close_3_slp_acc", d -> (float) d.getMom().getMom_close_3_slp_acc()),
            new FeatureDef("mom_close_8_slp_acc", d -> (float) d.getMom().getMom_close_8_slp_acc()),
            new FeatureDef("mom_close_14_slp_acc", d -> (float) d.getMom().getMom_close_14_slp_acc()),
            new FeatureDef("mom_close_3_slp_acc_atrn", d -> (float) d.getMom().getMom_close_3_slp_acc_atrn()),
            new FeatureDef("mom_close_8_slp_acc_atrn", d -> (float) d.getMom().getMom_close_8_slp_acc_atrn()),
            new FeatureDef("mom_close_14_slp_acc_atrn", d -> (float) d.getMom().getMom_close_14_slp_acc_atrn()),
            new FeatureDef("mom_cci_14_dlt", d -> (float) d.getMom().getMom_cci_14_dlt()),
            new FeatureDef("mom_cci_20_dlt", d -> (float) d.getMom().getMom_cci_20_dlt()),
            new FeatureDef("mom_cci_14_dst_mid", d -> (float) d.getMom().getMom_cci_14_dst_mid()),
            new FeatureDef("mom_cci_20_dst_mid", d -> (float) d.getMom().getMom_cci_20_dst_mid()),
            new FeatureDef("mom_roc_1", d -> (float) d.getMom().getMom_roc_1()),
            new FeatureDef("mom_roc_2", d -> (float) d.getMom().getMom_roc_2()),
            new FeatureDef("mom_roc_3", d -> (float) d.getMom().getMom_roc_3()),
            new FeatureDef("mom_roc_5", d -> (float) d.getMom().getMom_roc_5()),
            new FeatureDef("mom_ppo_hist_12_26_9_slp_w20", d -> (float) d.getMom().getMom_ppo_hist_12_26_9_slp_w20()),
            new FeatureDef("mom_trix_hist_9_slp_w20", d -> (float) d.getMom().getMom_trix_hist_9_slp_w20()),
            new FeatureDef("mom_tsi_hist_25_13_slp_w20", d -> (float) d.getMom().getMom_tsi_hist_25_13_slp_w20()),
            new FeatureDef("vol_taker_buy_ratio", d -> (float) d.getVol().getVol_taker_buy_ratio()),
            new FeatureDef("vol_taker_buy_sell_imbalance", d -> (float) d.getVol().getVol_taker_buy_sell_imbalance()),
            new FeatureDef("vol_taker_buy_ratio_rel_16", d -> (float) d.getVol().getVol_taker_buy_ratio_rel_16()),
            new FeatureDef("vol_taker_buy_ratio_slp_w20", d -> (float) d.getVol().getVol_taker_buy_ratio_slp_w20()),
            new FeatureDef("vol_taker_buy_sell_imbalance_slp_w20", d -> (float) d.getVol().getVol_taker_buy_sell_imbalance_slp_w20()),
            new FeatureDef("vol_volume_delta_1", d -> (float) d.getVol().getVol_volume_delta_1()),
            new FeatureDef("vol_volume_delta_3", d -> (float) d.getVol().getVol_volume_delta_3()),
            new FeatureDef("vol_trades_delta_1", d -> (float) d.getVol().getVol_trades_delta_1()),
            new FeatureDef("vol_trades_delta_3", d -> (float) d.getVol().getVol_trades_delta_3()),
            new FeatureDef("vol_quote_volume_delta_1", d -> (float) d.getVol().getVol_quote_volume_delta_1()),
            new FeatureDef("vol_quote_volume_delta_3", d -> (float) d.getVol().getVol_quote_volume_delta_3()),
            new FeatureDef("vol_act_trades_sp_16", d -> (float) d.getVol().getVol_act_trades_sp_16()),
            new FeatureDef("vol_act_trades_sp_32", d -> (float) d.getVol().getVol_act_trades_sp_32()),
            new FeatureDef("vol_act_trades_acc_16", d -> (float) d.getVol().getVol_act_trades_acc_16()),
            new FeatureDef("vol_act_trades_acc_32", d -> (float) d.getVol().getVol_act_trades_acc_32()),
            new FeatureDef("vol_act_quote_sp_16", d -> (float) d.getVol().getVol_act_quote_sp_16()),
            new FeatureDef("vol_act_quote_sp_32", d -> (float) d.getVol().getVol_act_quote_sp_32()),
            new FeatureDef("vol_act_quote_acc_16", d -> (float) d.getVol().getVol_act_quote_acc_16()),
            new FeatureDef("vol_act_quote_acc_32", d -> (float) d.getVol().getVol_act_quote_acc_32()),
            new FeatureDef("vol_volume_spike_score_16", d -> (float) d.getVol().getVol_volume_spike_score_16()),
            new FeatureDef("vol_trades_spike_score_16", d -> (float) d.getVol().getVol_trades_spike_score_16()),
            new FeatureDef("vol_microburst_volume_intensity_16", d -> (float) d.getVol().getVol_microburst_volume_intensity_16()),
            new FeatureDef("vol_microburst_trades_intensity_16", d -> (float) d.getVol().getVol_microburst_trades_intensity_16()),
            new FeatureDef("vol_microburst_combo_16", d -> (float) d.getVol().getVol_microburst_combo_16()),
            new FeatureDef("vol_microburst_slope_16", d -> (float) d.getVol().getVol_microburst_slope_16()),
            new FeatureDef("vol_pressure_slope_16", d -> (float) d.getVol().getVol_pressure_slope_16()),
            new FeatureDef("vol_vwap_distance", d -> (float) d.getVol().getVol_vwap_distance()),
            new FeatureDef("vol_ofi", d -> (float) d.getVol().getVol_ofi()),
            new FeatureDef("vol_ofi_rel_16", d -> (float) d.getVol().getVol_ofi_rel_16()),
            new FeatureDef("vol_ofi_slp_w20", d -> (float) d.getVol().getVol_ofi_slp_w20()),
            new FeatureDef("vol_bap", d -> (float) d.getVol().getVol_bap()),
            new FeatureDef("vol_bap_slope_16", d -> (float) d.getVol().getVol_bap_slope_16()),
            new FeatureDef("vol_bap_acc_16", d -> (float) d.getVol().getVol_bap_acc_16()),
            new FeatureDef("vol_svr", d -> (float) d.getVol().getVol_svr()),
            new FeatureDef("vol_svr_slp_w20", d -> (float) d.getVol().getVol_svr_slp_w20()),
            new FeatureDef("vol_svr_acc_5", d -> (float) d.getVol().getVol_svr_acc_5()),
            new FeatureDef("vol_svr_acc_10", d -> (float) d.getVol().getVol_svr_acc_10()),
            new FeatureDef("vlt_atr_7_chg", d -> (float) d.getVlt().getVlt_atr_7_chg()),
            new FeatureDef("vlt_atr_14_chg", d -> (float) d.getVlt().getVlt_atr_14_chg()),
            new FeatureDef("vlt_atr_21_chg", d -> (float) d.getVlt().getVlt_atr_21_chg()),
            new FeatureDef("vlt_range_atr_14_loc", d -> (float) d.getVlt().getVlt_range_atr_14_loc()),
            new FeatureDef("vlt_range_atr_14_loc_chg", d -> (float) d.getVlt().getVlt_range_atr_14_loc_chg()),
            new FeatureDef("vlt_atr_7_21_ratio", d -> (float) d.getVlt().getVlt_atr_7_21_ratio()),
            new FeatureDef("vlt_atr_7_21_expn", d -> (float) d.getVlt().getVlt_atr_7_21_expn()),
            new FeatureDef("vlt_atr_7_21_cmpr", d -> (float) d.getVlt().getVlt_atr_7_21_cmpr()),
            new FeatureDef("vlt_atr_7_slp", d -> (float) d.getVlt().getVlt_atr_7_slp()),
            new FeatureDef("vlt_atr_14_slp", d -> (float) d.getVlt().getVlt_atr_14_slp()),
            new FeatureDef("vlt_atr_21_slp", d -> (float) d.getVlt().getVlt_atr_21_slp()),
            new FeatureDef("vlt_std_14_chg", d -> (float) d.getVlt().getVlt_std_14_chg()),
            new FeatureDef("vlt_std_20_chg", d -> (float) d.getVlt().getVlt_std_20_chg()),
            new FeatureDef("vlt_std_50_chg", d -> (float) d.getVlt().getVlt_std_50_chg()),
            new FeatureDef("vlt_std_14_50_ratio", d -> (float) d.getVlt().getVlt_std_14_50_ratio()),
            new FeatureDef("vlt_std_14_50_expn", d -> (float) d.getVlt().getVlt_std_14_50_expn()),
            new FeatureDef("vlt_std_14_50_cmpr", d -> (float) d.getVlt().getVlt_std_14_50_cmpr()),
            new FeatureDef("vlt_std_14_48_ratio", d -> (float) d.getVlt().getVlt_std_14_48_ratio()),
            new FeatureDef("vlt_std_14_48_expn", d -> (float) d.getVlt().getVlt_std_14_48_expn()),
            new FeatureDef("vlt_std_14_48_cmpr", d -> (float) d.getVlt().getVlt_std_14_48_cmpr()),
            new FeatureDef("vlt_std_14_slp", d -> (float) d.getVlt().getVlt_std_14_slp()),
            new FeatureDef("vlt_std_20_slp", d -> (float) d.getVlt().getVlt_std_20_slp()),
            new FeatureDef("vlt_std_50_slp", d -> (float) d.getVlt().getVlt_std_50_slp()),
            new FeatureDef("vlt_boll_20_width_chg", d -> (float) d.getVlt().getVlt_boll_20_width_chg()),
            new FeatureDef("vlt_vol_sqz_bb_kelt_chg", d -> (float) d.getVlt().getVlt_vol_sqz_bb_kelt_chg()),
            new FeatureDef("vlt_vol_sqz_bb_kelt_20_chg", d -> (float) d.getVlt().getVlt_vol_sqz_bb_kelt_20_chg()),
            new FeatureDef("vlt_vol_gk_16_slp", d -> (float) d.getVlt().getVlt_vol_gk_16_slp()),
            new FeatureDef("vlt_vol_gk_32_slp", d -> (float) d.getVlt().getVlt_vol_gk_32_slp()),
            new FeatureDef("vlt_vol_park_16_slp", d -> (float) d.getVlt().getVlt_vol_park_16_slp()),
            new FeatureDef("vlt_vol_park_32_slp", d -> (float) d.getVlt().getVlt_vol_park_32_slp()),
            new FeatureDef("vlt_vol_rs_16_slp", d -> (float) d.getVlt().getVlt_vol_rs_16_slp()),
            new FeatureDef("vlt_vol_rs_32_slp", d -> (float) d.getVlt().getVlt_vol_rs_32_slp()),
            new FeatureDef("vlt_vol_gk_16_48_ratio", d -> (float) d.getVlt().getVlt_vol_gk_16_48_ratio()),
            new FeatureDef("vlt_vol_gk_32_48_ratio", d -> (float) d.getVlt().getVlt_vol_gk_32_48_ratio()),
            new FeatureDef("vlt_vol_park_16_48_ratio", d -> (float) d.getVlt().getVlt_vol_park_16_48_ratio()),
            new FeatureDef("vlt_vol_park_32_48_ratio", d -> (float) d.getVlt().getVlt_vol_park_32_48_ratio()),
            new FeatureDef("vlt_vol_rs_16_48_ratio", d -> (float) d.getVlt().getVlt_vol_rs_16_48_ratio()),
            new FeatureDef("vlt_vol_rs_32_48_ratio", d -> (float) d.getVlt().getVlt_vol_rs_32_48_ratio()),
            new FeatureDef("vlt_vol_rv_10_slp", d -> (float) d.getVlt().getVlt_vol_rv_10_slp()),
            new FeatureDef("vlt_vol_rv_30_slp", d -> (float) d.getVlt().getVlt_vol_rv_30_slp()),
            new FeatureDef("vlt_vol_rv_10_30_ratio", d -> (float) d.getVlt().getVlt_vol_rv_10_30_ratio()),
            new FeatureDef("vlt_vol_rv_10_48_ratio", d -> (float) d.getVlt().getVlt_vol_rv_10_48_ratio()),
            new FeatureDef("vlt_ewma_vol_20_slp", d -> (float) d.getVlt().getVlt_ewma_vol_20_slp()),
            new FeatureDef("vlt_ewma_vol_32_slp", d -> (float) d.getVlt().getVlt_ewma_vol_32_slp()),
            new FeatureDef("vlt_ewma_vol_20_48_ratio", d -> (float) d.getVlt().getVlt_ewma_vol_20_48_ratio()),
            new FeatureDef("vlt_ewma_vol_32_48_ratio", d -> (float) d.getVlt().getVlt_ewma_vol_32_48_ratio()),
            new FeatureDef("tim_minute_of_day", d -> (float) d.getTim().getTim_minute_of_day()),
            new FeatureDef("tim_day_of_week", d -> (float) d.getTim().getTim_day_of_week()),
            new FeatureDef("tim_session_asia", d -> (float) d.getTim().getTim_session_asia()),
            new FeatureDef("tim_session_europe", d -> (float) d.getTim().getTim_session_europe()),
            new FeatureDef("tim_session_ny", d -> (float) d.getTim().getTim_session_ny()),
            new FeatureDef("tim_sin_time", d -> (float) d.getTim().getTim_sin_time()),
            new FeatureDef("tim_cos_time", d -> (float) d.getTim().getTim_cos_time()),
            new FeatureDef("tim_day_of_month", d -> (float) d.getTim().getTim_day_of_month()),
            new FeatureDef("tim_sin_day_of_week", d -> (float) d.getTim().getTim_sin_day_of_week()),
            new FeatureDef("tim_cos_day_of_week", d -> (float) d.getTim().getTim_cos_day_of_week()),
            new FeatureDef("tim_overlap_asia_eur", d -> (float) d.getTim().getTim_overlap_asia_eur()),
            new FeatureDef("tim_overlap_eur_ny", d -> (float) d.getTim().getTim_overlap_eur_ny()),
            new FeatureDef("tim_candle_in_h1", d -> (float) d.getTim().getTim_candle_in_h1())
    );

    private static final Map<String, Integer> indexByKey;
    private static final int[] allMask;

    static {
        Map<String, Integer> map = new HashMap<>(REGISTRY.size());
        for (int i = 0; i < REGISTRY.size(); i++) {
            map.put(REGISTRY.get(i).key(), i);
        }
        indexByKey = Collections.unmodifiableMap(map);
        allMask = IntStream.range(0, REGISTRY.size()).toArray();
    }

    public int[] allMask() {
        return allMask.clone();
    }

    public int[] maskOf(List<String> keys) {
        int[] mask = new int[keys.size()];
        for (int i = 0; i < keys.size(); i++) {
            Integer idx = indexByKey.get(keys.get(i));
            if (idx == null) {
                throw new IllegalArgumentException("Feature not found in REGISTRY: " + keys.get(i));
            }
            mask[i] = idx;
        }
        return mask;
    }

    public List<String> allKeys() {
        return REGISTRY.stream().map(FeatureDef::key).toList();
    }

    public float[] buildFeatures(AssemblerDto dto, int[] mask) {
        float[] out = new float[mask.length];
        for (int j = 0; j < mask.length; j++) {
            FeatureDef def = REGISTRY.get(mask[j]);
            try {
                out[j] = def.fn().get(dto);
            } catch (Exception e) {
                out[j] = Float.NaN;
            }
        }
        return out;
    }

    public float[] buildFeatures(AssemblerDto dto) {
        return buildFeatures(dto, allMask);
    }
}
