server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
spring:
  application:
    name: Yacamin-Rafael
  mongodb:
    uri: "${MONGODB_URI:mongodb://root:T%23fu1964@77.37.54.142:5432/yacamin-gabriel?authSource=admin&directConnection=true}"
mongodb:
  mikhael:
    uri: "${MONGODB_MIKHAEL_URI:mongodb://root:T%23fu1964@77.37.54.142:5432/yacamin-mikhael?authSource=admin&directConnection=true}"
polymarket:
  wallet-address: "0xBfEB032385e38b733150aacc91F5161815d65df0"
  private-key: "0xe458802085a329c2011118d222b5b82b0e457df6623d7d777ec2c20a2e523b75"
  ws:
    api-key: "019ce365-e310-76ee-8d09-757c74d132a1"
    secret: "rRQIioMjEwLn9dsOtvEkQCI5tePUbHv8xLHJiqxAflA="
    pass: "63c7e2f6aa5a65fb46c3d1e747bc4376ad0438c9ae4105556670bd4624a27f38"
  paths:
    clob:
      rest: https://clob.polymarket.com
    gamma:
      markets:
        rest: https://gamma-api.polymarket.com/markets
  endpoints:
    clob:
      book: /book
    gamma:
      markets:
        slug: /slug
app:
  auth:
    password-hash: "${DASHBOARD_PASSWORD_HASH:$2a$10$sU99hPYdqD4uXPwirxIco.YjGPRysOPOuDToM95BFSLuWWotpRKB.}"
polygon:
  alchemy:
    api-key: "K2T2FCFT5VQX2n7Alttmj"
    ws: "wss://polygon-mainnet.g.alchemy.com/v2/${polygon.alchemy.api-key}"
  ctf-contract: "0x4D97DCd97eC945f40cF65F87097ACe5EA0476045"
binance:
  paths:
    spot:
      ws: wss://stream.binance.com:9443/ws
      rest: https://api.binance.com
  endpoints:
    spot:
      klines: /api/v3/klines


