package br.com.yacamin.rafael.domain.scylla.entity.indicator;
import java.time.Instant;

public interface TrendIndicatorEntity {
    Instant getOpenTime();
    void setOpenTime(Instant openTime);
    double getTrd_aligment_ema_8_20_50_delta();
    void setTrd_aligment_ema_8_20_50_delta(double value);
    double getTrd_alignment_ema_8_20_50_normalized();
    void setTrd_alignment_ema_8_20_50_normalized(double value);
    double getTrd_alignment_ema_8_20_50_score();
    void setTrd_alignment_ema_8_20_50_score(double value);
    double getTrd_cross_ema_20_50_delta_atrn();
    void setTrd_cross_ema_20_50_delta_atrn(double value);
    double getTrd_cross_ema_8_20_delta_atrn();
    void setTrd_cross_ema_8_20_delta_atrn(double value);
    double getTrd_delta_close_ema_20_atrn();
    void setTrd_delta_close_ema_20_atrn(double value);
    double getTrd_delta_close_ema_50_atrn();
    void setTrd_delta_close_ema_50_atrn(double value);
    double getTrd_delta_close_ema_8_atrn();
    void setTrd_delta_close_ema_8_atrn(double value);
    double getTrd_delta_ema_20_50_atrn();
    void setTrd_delta_ema_20_50_atrn(double value);
    double getTrd_delta_ema_8_20_atrn();
    void setTrd_delta_ema_8_20_atrn(double value);
    double getTrd_di_diff_14();
    void setTrd_di_diff_14(double value);
    double getTrd_dist_close_ema_20_atrn();
    void setTrd_dist_close_ema_20_atrn(double value);
    double getTrd_dist_close_ema_50_atrn();
    void setTrd_dist_close_ema_50_atrn(double value);
    double getTrd_dist_close_ema_8_atrn();
    void setTrd_dist_close_ema_8_atrn(double value);
    double getTrd_dist_ema_20_50_atrn();
    void setTrd_dist_ema_20_50_atrn(double value);
    double getTrd_dist_ema_8_20_atrn();
    void setTrd_dist_ema_8_20_atrn(double value);
    double getTrd_dist_ema_8_50_atrn();
    void setTrd_dist_ema_8_50_atrn(double value);
    double getTrd_ema_20_slp_acc_atrn();
    void setTrd_ema_20_slp_acc_atrn(double value);
    double getTrd_ema_20_slp_atrn();
    void setTrd_ema_20_slp_atrn(double value);
    double getTrd_ema_50_slp_acc_atrn();
    void setTrd_ema_50_slp_acc_atrn(double value);
    double getTrd_ema_50_slp_atrn();
    void setTrd_ema_50_slp_atrn(double value);
    double getTrd_ema_8_slp_acc_atrn();
    void setTrd_ema_8_slp_acc_atrn(double value);
    double getTrd_ema_8_slp_atrn();
    void setTrd_ema_8_slp_atrn(double value);
    double getTrd_ratio_ema_20_50();
    void setTrd_ratio_ema_20_50(double value);
    double getTrd_ratio_ema_8_20();
    void setTrd_ratio_ema_8_20(double value);
    double getTrd_ratio_ema_8_50();
    void setTrd_ratio_ema_8_50(double value);
}
